### ISSUE TITLE
Enhancement: Add bam slicing option

### ISSUE THREAD

**Issue by harish0201** [sbslee/fuc#11]
Hi!

I'm not too sure if a lot of people do this, but I generally like to split up my bam into sequence wise bams, for variant calling or genome polishing etc.

This would be a really useful command to have in general!

**Comment by sbslee** [comment]
@harish0201, thanks for the idea! I had to do that multiple times to create "mini" BAMs. I will definitely add the command in v0.8.0 (will call it something like ``bam_slice``).

**Comment by sbslee** [comment]
@harish0201, 

I just added a new command called `bam_slice` to the v0.8.0 version of `fuc`:

```
(fuc) sbslee@Seung-beens-MacBook-Air docs % fuc -v
fuc 0.8.0
(fuc) sbslee@Seung-beens-MacBook-Air docs % fuc bam_slice -h
usage: fuc bam_slice [-h] [--no_index] input_bam region output_bam

This command will slice a BAM file. By default, the command will create a accompanying index file (.bai) for the output BAM file.

positional arguments:
  input_bam   input BAM file
  region      target region
  output_bam  output BAM file

optional arguments:
  -h, --help  show this help message and exit
  --no_index  use to this flag to skip indexing
```

To install the latest v0.8.0 version, clone the repository and install `fuc` in the following way:

```
$ git clone https://github.com/sbslee/fuc
$ cd fuc
$ git checkout 0.8.0-dev
$ pip install .
```

Let me know what you think! If you have additional feature requests, feel free to share as well (in a separate issue).

**Comment by harish0201** [comment]
Thank you!
