### ISSUE TITLE
Error during installation fuc via conda

### ISSUE THREAD

**Issue by emoranska** [sbslee/fuc#52]
Hi @sbslee again,
I have a problem with installation fuc on the new computer with Ubuntu. When I try to run installation via conda, I receive such a call:

```
(burak) ➜  fuc git:(main) conda install -c bioconda fuc
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.                                                                                                                                                    failed                                                                                                                                                                                                     

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - python=3.10 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.27`
```

Finally, I have installed required packages but fuc not. Any ideas how to fix it and install fuc? I've tried to do it wit git clone but then I've got an error too.

Thanks a lot!

**Comment by emoranska** [comment]
Downgrading python version to 3.7 in conda environment has solved the problem :)

**Comment by sbslee** [comment]
@emoranska, glad you figured it out :) FYI, it you only need `fuc` installed, the recommended way to download/install is:

```
$ conda create -n fuc -c bioconda fuc
```

This ensures that your environment always works with `fuc`. If you need to install `fuc` AND other packages, still, the recommended way to download/install all the dependencies is:

```
$ conda create -n complex-env -c conda-forge -c bioconda fuc other_package1 other_package2
```

Again, this ensures that the final environment is compatible with all the requested packages. If you try to install multiple packages sequentially, there's a high chance you will encounter dependency conflicts like the one you reported.

Hope this helps.
