### ISSUE TITLE
[VCF] Issue reading vcf from mutect2, strelka2

### ISSUE THREAD

**Issue by ironb25** [sbslee/fuc#62]
Hello,

I am trying to read vcf file from mutect2 and strelka2 and getting this error below.

Code:

```
from fuc import pyvcf
vf = pyvcf.VcfFrame.from_file('mutect2.vcf')
vf.df

```

Error: 
```
DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  vf = pyvcf.Vcf
```

Could you please help?

Thanks
Rohan

**Comment by sbslee** [comment]
The conversation has been moved to email, and the problem was indeed caused because the OP was using an old version of fuc. Reinstalling the latest version resolved the issue. Closing this.
