### ISSUE TITLE
[MAF] Update Ensembl VEP consequences mapping

### ISSUE THREAD

**Issue by brianryu87** [sbslee/fuc#68]
Hi Steven,

I tried running `fuc maf-vcf2maf in.vcf > out.maf` on a VEP-annotated VCF today but got an error as below:
`ValueError: Found unknown Ensembl VEP consequence: splice_donor_region_variant`
I'm guessing there are additional consequence terms that need to be added?

Thank you for all your hard work. `fuc` is fabulous.

p.s. My version of VEP is 109.3

**Comment by sbslee** [comment]
@brianryu87,

Thank you for this post!

You are absolutely correct. The consequences database in the `pymaf` module was last updated on May 31, 2021. Looking at the Ensembl VEP [page](https://m.ensembl.org/info/genome/variation/prediction/predicted_data.html), I can confirm that they've added five new consequences:

```
splice_donor_5th_base_variant
splice_donor_region_variant
splice_polypyrimidine_tract_variant
coding_transcript_variant
sequence_variant
```

I've added these consequences in the `0.37.0-dev` branch, which you can access by:

```
$ git clone https://github.com/sbslee/fuc
$ cd fuc
$ git checkout 0.37.0-dev
$ pip install .
```

However, please note that, AFAIK, these consequences don't have mappings yet for `Variant_Classification` in MAF (e.g. `splice_donor_variant` to `Splice_Site`). Therefore, I've just put `AMBIGUOUS` as their mappings for now (e.g. `splice_donor_5th_base_variant` to `AMBIGUOUS`. Let me know if you happen to know their correct mappings.    

That said, I'd greatly appreciate it if you could test this new version and let me know if everything works as expected. If you're satisfied with it, I will go ahead and release the official version of `0.37.0`. Thanks!

**Comment by brianryu87** [comment]
Hi Steven, 

Thank you for the fast response!
I tested with the same VCF file and it seems to work well!

From the short research I've done, I agree that there is no official mapping yet for those five new consequences, and that mapping them as `AMBIGUOUS` would be the only option at the moment.

Anyway, thank you for adding the terms!

**Comment by sbslee** [comment]
Thank you so much for testing it out! I will release the official version of `0.37.0` this week.
