### ISSUE TITLE
[MAF] UnboundLocalError: local variable 'columns' referenced before assignment

### ISSUE THREAD

**Issue by Bo-UT** [sbslee/fuc#73]
Hi, 

I tried to run `fuc maf-vcf2maf input.vcf > output.maf` with the annotated `vcf` from `vep`. I got the error saying
```
  File "/Users/bzhao2/miniconda3/envs/single-cell/lib/python3.10/site-packages/fuc/api/pyvcf.py", line 2429, in from_string
    columns[0] = 'CHROM'
UnboundLocalError: local variable 'columns' referenced before assignment
```

I also tried to load the annotated `vcf` by `pyvcf.VcfFrame.from_file`, but got the same error. It did work for the `vcf` file without annotation. 

Thank you.

**Comment by sbslee** [comment]
Hi @Bo-UT,

1. What version of `fuc` are you currently using?
2. Can you share your VCF file with me via sbstevenlee@gmail.com? It's difficult to solve a problem without seeing some data. I don't need to see your entire dataset; I just need a minimal example to replicate the issue. However, no worries if you can't share any data. We can still work this out.
3. My best guess is that your VCF is missing the column headers. The error is complaining the fact that the VCF does not have a line that starts with `#CHROM` and therefore the `columns` variable is never set:

https://github.com/sbslee/fuc/blob/7b0fbfbd1c0f3f42274f75f8875cebe5b74afdb3/fuc/api/pyvcf.py#L2422-L2433

**Comment by Bo-UT** [comment]
Hi @sbslee , 

Thank you! 
I am running the latest version of `fuc`.  Yes, my `.vcf` file missed the line starting with `#CHROM`. I reran `ensembl-vep` with the output option `--vcf` and now it works. Thanks for the great tool!!

I have one more question regarding `maf-vcf2maf`. I got an error 
```
File "/Users/bzhao2/miniconda3/envs/single-cell/lib/python3.10/site-packages/fuc/api/pymaf.py", line 451, in from_vcf
    ncbi_build = re.search(r'assembly="(.*?)"', line).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
I guess my `.vcf` file is missing `assembly=`. Our data is from hamster, and the reference is in form of `contig`, not `chromosome`. Do you have suggestions on the conversion?  I sent you the `.vcf` file. Thank you!
